import { InteractionResult, Medicine, RiskLevel } from '../types';

export const MOCK_MEDICINES: Medicine[] = [
  {
    id: 'm1',
    name: '타이레놀500mg',
    genericName: '아세트아미노펜',
    manufacturer: '한국얀센',
    category: '해열진통제',
    isPrescription: false,
    effects: '발열 및 두통, 신경통, 근육통, 월경통 등에 의한 통증 완화',
    dosage: '성인 1회 1-2정, 1일 3-4회 (4-6시간 간격), 1일 최대 4,000mg',
    warnings: [
      '간장애 환자는 의사와 상의',
      '알코올과 함께 복용 시 간 손상 위험 증가',
      '1일 4,000mg 초과 복용 금지',
    ],
    storage: '실온 보관, 직사광선 피함',
    ingredients: ['아세트아미노펜 500mg'],
  },
  {
    id: 'm2',
    name: '부루펜정200mg',
    genericName: '이부프로펜',
    manufacturer: '삼일제약',
    category: '비스테로이드성 소염진통제(NSAIDs)',
    isPrescription: false,
    effects: '두통, 치통, 생리통, 근육통, 관절통, 발열의 완화',
    dosage: '성인 1회 1-2정, 1일 3-4회 (식후)',
    warnings: [
      '위장장애 환자 주의',
      '아스피린 알레르기 환자 금기',
      '임신 말기 금기',
      '신장 질환자 주의',
    ],
    storage: '실온 보관',
    ingredients: ['이부프로펜 200mg'],
  },
  {
    id: 'm3',
    name: '아스피린프로텍트정100mg',
    genericName: '아세틸살리실산',
    manufacturer: '바이엘코리아',
    category: '항혈전제',
    isPrescription: true,
    effects: '심근경색, 뇌졸중 등 혈전 예방',
    dosage: '1일 1회 1정 (식후)',
    warnings: [
      '15세 이하 소아 금기 (라이증후군 위험)',
      '출혈 위험 증가',
      '위궤양 환자 금기',
      '수술 전 7일 중단 권고',
    ],
    storage: '실온 보관',
    ingredients: ['아세틸살리실산 100mg'],
  },
  {
    id: 'm4',
    name: '판콜에이내복액',
    genericName: '복합감기약',
    manufacturer: '동화약품',
    category: '종합감기약',
    isPrescription: false,
    effects: '감기의 제증상 완화 (콧물, 코막힘, 재채기, 인후통, 발열)',
    dosage: '성인 1회 1병, 1일 3회 (식후 30분)',
    warnings: [
      '아세트아미노펜 함유 - 타이레놀과 중복 복용 주의',
      '운전 전 복용 주의 (졸음)',
      '음주 시 복용 금지',
    ],
    storage: '실온 보관',
    ingredients: ['아세트아미노펜', '클로르페니라민', '슈도에페드린'],
  },
  {
    id: 'm5',
    name: '훼스탈플러스정',
    genericName: '소화효소제',
    manufacturer: '한독',
    category: '소화제',
    isPrescription: false,
    effects: '소화불량, 식욕감퇴, 과식, 식체, 위부팽만감',
    dosage: '성인 1회 1-2정, 1일 3회 (식후)',
    warnings: ['특별한 주의사항 없음'],
    storage: '실온 보관',
    ingredients: ['판크레아틴', '판프로신', '판셀라제'],
  },
  {
    id: 'm6',
    name: '암로디핀정5mg',
    genericName: '암로디핀',
    manufacturer: '한미약품',
    category: '고혈압 치료제(칼슘채널차단제)',
    isPrescription: true,
    effects: '고혈압, 협심증 치료',
    dosage: '1일 1회 1정',
    warnings: [
      '자몽주스와 함께 복용 금지 (혈중농도 상승)',
      '갑작스러운 중단 금지',
      '간기능 장애 환자 용량 조절',
    ],
    storage: '실온 보관',
    ingredients: ['암로디핀베실산염 6.94mg(암로디핀으로서 5mg)'],
  },
  {
    id: 'm7',
    name: '메트포르민정500mg',
    genericName: '메트포르민',
    manufacturer: '대웅제약',
    category: '경구 혈당강하제',
    isPrescription: true,
    effects: '제2형 당뇨병 치료',
    dosage: '1일 2-3회, 식사와 함께',
    warnings: [
      '신장기능 저하 환자 주의',
      '음주 금지 (젖산산증 위험)',
      'CT 조영제 사용 전후 48시간 중단',
    ],
    storage: '실온 보관',
    ingredients: ['메트포르민염산염 500mg'],
  },
  {
    id: 'm8',
    name: '와파린정2mg',
    genericName: '와파린',
    manufacturer: '제일약품',
    category: '항응고제',
    isPrescription: true,
    effects: '혈전 예방 및 치료',
    dosage: '의사 처방에 따라 (INR 모니터링 필수)',
    warnings: [
      '비타민K 함유 음식(녹색채소) 주의',
      '여러 약물과 상호작용',
      '출혈 위험 - 정기 검사 필수',
      '임부 금기',
    ],
    storage: '실온 보관',
    ingredients: ['와파린나트륨 2mg'],
  },
  {
    id: 'm9',
    name: '게보린정',
    genericName: '복합 진통제',
    manufacturer: '삼진제약',
    category: '해열진통제',
    isPrescription: false,
    effects: '두통, 치통, 생리통, 근육통, 관절통, 발열의 일시적 완화',
    dosage: '성인 1회 1정, 1일 3회 (4시간 이상 간격)',
    warnings: ['소화성 궤양 환자 주의', '15세 미만 복용 금지', '아세트아미노펜 함유'],
    storage: '실온 보관',
    ingredients: ['아세트아미노펜', '이소프로필안티피린', '카페인'],
  },
  {
    id: 'm10',
    name: '펜잘큐정',
    genericName: '복합 진통제',
    manufacturer: '종근당',
    category: '해열진통제',
    isPrescription: false,
    effects: '두통, 치통, 생리통, 근육통, 관절통, 신경통 완화',
    dosage: '성인 1회 1-2정, 1일 3회 (식후 30분)',
    warnings: ['공복 복용 시 위장장애', '카페인 함유 - 카페인 음료와 중복 주의'],
    storage: '실온 보관',
    ingredients: ['아세트아미노펜', '에텐자미드', '카페인'],
  },
  {
    id: 'm11',
    name: '이지엔6애니연질캡슐',
    genericName: '덱시부프로펜',
    manufacturer: '대웅제약',
    category: '비스테로이드성 소염진통제(NSAIDs)',
    isPrescription: false,
    effects: '진통, 해열, 소염 (생리통, 두통, 치통)',
    dosage: '성인 1회 1캡슐, 1일 3회',
    warnings: ['위장장애 주의', '신장질환자 주의', '임신 말기 금기'],
    storage: '실온 보관',
    ingredients: ['덱시부프로펜 300mg'],
  },
  {
    id: 'm12',
    name: '나프록센정250mg',
    genericName: '나프록센',
    manufacturer: '국제약품',
    category: '비스테로이드성 소염진통제(NSAIDs)',
    isPrescription: false,
    effects: '관절염, 근육통, 생리통, 두통 등의 통증과 염증 완화',
    dosage: '성인 1회 1정, 1일 2회 (식후)',
    warnings: ['위장장애', '심혈관 질환 환자 장기 복용 주의', '신장 부담'],
    storage: '실온 보관',
    ingredients: ['나프록센 250mg'],
  },
  {
    id: 'm13',
    name: '화이투벤큐연질캡슐',
    genericName: '복합감기약',
    manufacturer: '한국다케다제약',
    category: '종합감기약',
    isPrescription: false,
    effects: '감기로 인한 발열, 두통, 인후통, 콧물, 기침 완화',
    dosage: '성인 1회 1캡슐, 1일 3회 (식후)',
    warnings: ['졸음 - 운전 전 복용 금지', '아세트아미노펜 중복 주의', '음주 금지'],
    storage: '실온 보관',
    ingredients: ['아세트아미노펜', '클로르페니라민', '슈도에페드린', '덱스트로메토르판'],
  },
  {
    id: 'm14',
    name: '콘택600',
    genericName: '복합감기약',
    manufacturer: '유한양행',
    category: '종합감기약',
    isPrescription: false,
    effects: '코감기 (콧물, 코막힘, 재채기) 완화',
    dosage: '성인 1회 1캡슐, 1일 2회 (12시간 간격)',
    warnings: ['졸음', '고혈압 환자 주의 (슈도에페드린)', '전립선비대 환자 주의'],
    storage: '실온 보관',
    ingredients: ['슈도에페드린', '클로르페니라민'],
  },
  {
    id: 'm15',
    name: '베아제정',
    genericName: '소화효소제',
    manufacturer: '대웅제약',
    category: '소화제',
    isPrescription: false,
    effects: '소화불량, 식욕부진, 과식, 식체, 위부팽만감 완화',
    dosage: '성인 1회 1정, 1일 3회 (식후)',
    warnings: ['특이사항 적음'],
    storage: '실온 보관',
    ingredients: ['비오디아스타제', '판크레아틴', '리파제'],
  },
  {
    id: 'm16',
    name: '까스활명수큐액',
    genericName: '복합 소화제',
    manufacturer: '동화약품',
    category: '소화제',
    isPrescription: false,
    effects: '소화불량, 과식, 식체, 위부팽만감, 구역질, 트림',
    dosage: '성인 1회 1병, 필요시 (1일 3회 이내)',
    warnings: ['임부 주의', '소아 복용 주의'],
    storage: '실온 보관, 흔들어 복용',
    ingredients: ['현호색', '아출', '진피', '계피', '정향', '육두구'],
  },
  {
    id: 'm17',
    name: '겔포스엠현탁액',
    genericName: '제산제',
    manufacturer: '보령제약',
    category: '제산제',
    isPrescription: false,
    effects: '속쓰림, 신트림, 위산과다, 위·십이지장궤양 보조요법',
    dosage: '성인 1회 1포, 1일 3-4회 (식후 1-2시간, 취침 전)',
    warnings: ['다른 약과 2시간 간격', '신장질환자 주의'],
    storage: '실온 보관',
    ingredients: ['인산알루미늄겔', '수산화마그네슘', '시메티콘'],
  },
  {
    id: 'm18',
    name: '무코스타정100mg',
    genericName: '레바미피드',
    manufacturer: '오츠카제약',
    category: '위점막 보호제',
    isPrescription: true,
    effects: '위염, 위궤양의 위 점막 손상 개선',
    dosage: '성인 1회 1정, 1일 3회 (식후)',
    warnings: ['장기 복용 시 의사 상담', '드물게 알레르기'],
    storage: '실온 보관',
    ingredients: ['레바미피드 100mg'],
  },
  {
    id: 'm19',
    name: '넥시움정20mg',
    genericName: '에스오메프라졸',
    manufacturer: '아스트라제네카',
    category: '양성자펌프억제제(PPI)',
    isPrescription: true,
    effects: '역류성 식도염, 위·십이지장궤양 치료',
    dosage: '1일 1회 1정 (식전)',
    warnings: ['장기 복용 시 골다공증 위험', '클로피도그렐과 상호작용', '비타민 B12 흡수 저하'],
    storage: '실온 보관',
    ingredients: ['에스오메프라졸 20mg'],
  },
  {
    id: 'm20',
    name: '지르텍정10mg',
    genericName: '세티리진',
    manufacturer: 'UCB제약',
    category: '항히스타민제 (알레르기약)',
    isPrescription: false,
    effects: '알레르기 비염, 만성 두드러기, 가려움 완화',
    dosage: '성인 1일 1회 1정',
    warnings: ['졸음 가능성 (1세대보다는 적음)', '신장기능 저하자 용량 조절'],
    storage: '실온 보관',
    ingredients: ['세티리진염산염 10mg'],
  },
  {
    id: 'm21',
    name: '클라리틴정10mg',
    genericName: '로라타딘',
    manufacturer: '바이엘',
    category: '항히스타민제 (알레르기약)',
    isPrescription: false,
    effects: '알레르기성 비염, 두드러기, 가려움증 완화',
    dosage: '성인 1일 1회 1정',
    warnings: ['졸음 적음 (2세대)', '간 기능 저하자 격일 복용'],
    storage: '실온 보관',
    ingredients: ['로라타딘 10mg'],
  },
  {
    id: 'm22',
    name: '알레그라정120mg',
    genericName: '펙소페나딘',
    manufacturer: '사노피',
    category: '항히스타민제 (알레르기약)',
    isPrescription: false,
    effects: '계절성 알레르기 비염, 만성 두드러기 증상 완화',
    dosage: '성인 1일 1회 1정',
    warnings: ['과일주스(자몽/오렌지/사과)와 함께 복용 시 효과 감소'],
    storage: '실온 보관',
    ingredients: ['펙소페나딘염산염 120mg'],
  },
  {
    id: 'm23',
    name: '둘코락스에스장용정',
    genericName: '비사코딜',
    manufacturer: '베링거인겔하임',
    category: '변비약',
    isPrescription: false,
    effects: '일시적 변비 완화',
    dosage: '성인 1회 1-2정, 취침 전 (효과 6-12시간 후)',
    warnings: ['우유/제산제와 함께 복용 금지 (장용성 손상)', '장기 복용 금지', '복통 시 중단'],
    storage: '실온 보관',
    ingredients: ['비사코딜 5mg'],
  },
  {
    id: 'm24',
    name: '마그밀정500mg',
    genericName: '수산화마그네슘',
    manufacturer: '삼남제약',
    category: '변비약/제산제',
    isPrescription: false,
    effects: '변비, 위산과다, 속쓰림 완화',
    dosage: '성인 1회 1-2정, 1일 3회',
    warnings: ['신장질환자 금기', '다른 약과 2시간 간격', '장기 복용 주의'],
    storage: '실온 보관',
    ingredients: ['수산화마그네슘 500mg'],
  },
  {
    id: 'm25',
    name: '베나치오에프액',
    genericName: '복합 소화제',
    manufacturer: '동아제약',
    category: '소화제',
    isPrescription: false,
    effects: '소화불량, 식체, 위부팽만감, 구역, 구토',
    dosage: '성인 1회 1병, 1일 3회 (식후)',
    warnings: ['임부 주의'],
    storage: '실온 보관',
    ingredients: ['현호색', '아출', '회향', '계피'],
  },
  {
    id: 'm26',
    name: '아목시실린캡슐250mg',
    genericName: '아목시실린',
    manufacturer: '종근당',
    category: '페니실린계 항생제',
    isPrescription: true,
    effects: '세균성 감염 (인후염, 중이염, 폐렴, 요로감염 등) 치료',
    dosage: '성인 1회 1-2캡슐, 1일 3회 (8시간 간격)',
    warnings: ['페니실린 알레르기 환자 금기', '처방 기간 끝까지 복용', '경구피임약 효과 감소'],
    storage: '실온 보관',
    ingredients: ['아목시실린 250mg'],
  },
  {
    id: 'm27',
    name: '졸피뎀정10mg',
    genericName: '졸피뎀',
    manufacturer: '한미약품',
    category: '수면유도제',
    isPrescription: true,
    effects: '단기 불면증 치료',
    dosage: '성인 1일 1회 1정, 취침 직전',
    warnings: ['의존성/내성 - 단기 사용', '음주 금지', '운전/기계 조작 금지', '몽유 행동 보고됨'],
    storage: '실온 보관',
    ingredients: ['졸피뎀타르타르산염 10mg'],
  },
  {
    id: 'm28',
    name: '리피토정10mg',
    genericName: '아토르바스타틴',
    manufacturer: '비아트리스(화이자)',
    category: '고지혈증 치료제 (스타틴)',
    isPrescription: true,
    effects: '고콜레스테롤혈증 치료, 심혈관질환 예방',
    dosage: '1일 1회 1정 (취침 전 권장)',
    warnings: ['근육통/무력감 시 의사 상담 (횡문근융해증)', '자몽주스 주의', '간 기능 모니터링'],
    storage: '실온 보관',
    ingredients: ['아토르바스타틴칼슘 10mg'],
  },
  {
    id: 'm29',
    name: '코자정50mg',
    genericName: '로사르탄',
    manufacturer: 'MSD',
    category: '고혈압 치료제 (ARB)',
    isPrescription: true,
    effects: '고혈압, 당뇨병성 신증 치료',
    dosage: '1일 1회 1정',
    warnings: ['임부 금기 (태아 위험)', '칼륨 보충제 주의', '수분 부족 시 저혈압'],
    storage: '실온 보관',
    ingredients: ['로사르탄칼륨 50mg'],
  },
  {
    id: 'm30',
    name: '신지로이드정0.1mg',
    genericName: '레보티록신',
    manufacturer: '부광약품',
    category: '갑상선호르몬제',
    isPrescription: true,
    effects: '갑상선기능저하증 치료',
    dosage: '1일 1회 1정 (아침 공복, 식사 30분 전)',
    warnings: ['다른 약과 4시간 이상 간격 권장', '평생 복용 필요할 수 있음', '임의 중단 금지'],
    storage: '실온 보관',
    ingredients: ['레보티록신나트륨 0.1mg'],
  },
  {
    id: 'm31',
    name: '센트룸종합비타민',
    genericName: '종합비타민',
    manufacturer: '한국화이자',
    category: '건강기능식품/비타민',
    isPrescription: false,
    effects: '균형 잡힌 비타민/미네랄 보충',
    dosage: '성인 1일 1정 (식후)',
    warnings: ['과량 복용 금지', '식품과 함께 복용 권장'],
    storage: '실온 보관',
    ingredients: ['비타민 A/B/C/D/E', '철', '아연', '칼슘 등'],
  },
  {
    id: 'm32',
    name: '액티피드정',
    genericName: '복합 비염약',
    manufacturer: 'GSK',
    category: '항히스타민/충혈제거제',
    isPrescription: false,
    effects: '비염, 감기로 인한 콧물, 코막힘, 재채기',
    dosage: '성인 1회 1정, 1일 3회',
    warnings: ['졸음 - 운전 금지', '고혈압/심장질환 주의', '음주 금지'],
    storage: '실온 보관',
    ingredients: ['트리프롤리딘', '슈도에페드린'],
  },
  {
    id: 'm33',
    name: '히알루론산점안액0.1%',
    genericName: '히알루론산나트륨',
    manufacturer: '삼일제약',
    category: '인공눈물',
    isPrescription: false,
    effects: '안구건조증, 눈의 피로감 완화',
    dosage: '1회 1-2방울, 1일 5-6회 점안',
    warnings: ['콘택트렌즈 착용 시 의사 상담', '개봉 후 1개월 이내 사용'],
    storage: '실온 보관',
    ingredients: ['히알루론산나트륨 1mg/ml'],
  },
  {
    id: 'm34',
    name: '인사돌플러스정',
    genericName: '복합 잇몸약',
    manufacturer: '동국제약',
    category: '잇몸약',
    isPrescription: false,
    effects: '치주염, 잇몸 출혈, 잇몸 부종 완화',
    dosage: '성인 1회 1정, 1일 3회',
    warnings: ['증상 지속 시 치과 진료 권장'],
    storage: '실온 보관',
    ingredients: ['옥수수불검화정량추출물', '후박엑스'],
  },
  {
    id: 'm35',
    name: '스코폴라민정',
    genericName: '디멘히드리네이트',
    manufacturer: '삼진제약',
    category: '멀미약',
    isPrescription: false,
    effects: '멀미, 어지러움, 구역, 구토 예방 및 완화',
    dosage: '성인 1회 1-2정, 탑승 30분 전',
    warnings: ['졸음 - 운전 금지', '녹내장 환자 금기', '전립선비대 주의'],
    storage: '실온 보관',
    ingredients: ['디멘히드리네이트 50mg'],
  },
  {
    id: 'm36',
    name: '센시아정',
    genericName: '은행엽 추출물',
    manufacturer: '동아ST',
    category: '말초혈액순환 개선제',
    isPrescription: false,
    effects: '말초혈액순환 장애로 인한 어지러움, 이명, 손발 저림 완화',
    dosage: '성인 1회 1정, 1일 3회',
    warnings: ['항응고제 복용 시 출혈 위험 - 의사 상담', '수술 전 2주 중단'],
    storage: '실온 보관',
    ingredients: ['은행엽 건조엑스 40mg'],
  },
];

interface InteractionRule {
  pair: [string, string];
  level: RiskLevel;
  description: string;
  recommendation: string;
}

const INTERACTION_RULES: InteractionRule[] = [
  {
    pair: ['m1', 'm4'],
    level: 'high',
    description: '두 제품 모두 아세트아미노펜을 함유하여 1일 최대 용량(4,000mg)을 초과할 위험이 있습니다.',
    recommendation: '동시 복용을 피하고, 복용 전 약사와 상담하세요.',
  },
  {
    pair: ['m2', 'm3'],
    level: 'high',
    description: '두 약 모두 위장 출혈 및 신장 부담 위험이 있어 함께 복용 시 위험이 증가합니다.',
    recommendation: '의사/약사 상담 없이 동시 복용하지 마세요.',
  },
  {
    pair: ['m3', 'm8'],
    level: 'critical',
    description: '아스피린과 와파린은 출혈 위험을 크게 증가시킵니다.',
    recommendation: '의사 처방 없이 절대 함께 복용하지 마세요.',
  },
  {
    pair: ['m6', 'm6'],
    level: 'medium',
    description: '암로디핀은 자몽주스와 상호작용할 수 있습니다.',
    recommendation: '자몽주스 섭취를 피하세요.',
  },
  {
    pair: ['m7', 'm7'],
    level: 'high',
    description: '메트포르민은 음주 시 젖산산증 위험이 있습니다.',
    recommendation: '복용 중 음주를 피하세요.',
  },
];

export function checkInteractions(medicineIds: string[]): InteractionResult[] {
  const results: InteractionResult[] = [];
  const seen = new Set<string>();
  for (let i = 0; i < medicineIds.length; i++) {
    for (let j = i; j < medicineIds.length; j++) {
      const a = medicineIds[i];
      const b = medicineIds[j];
      const key = [a, b].sort().join('+');
      if (seen.has(key)) continue;
      seen.add(key);
      const rule = INTERACTION_RULES.find(
        (r) =>
          (r.pair[0] === a && r.pair[1] === b) ||
          (r.pair[0] === b && r.pair[1] === a),
      );
      if (!rule) continue;
      const nameA = MOCK_MEDICINES.find((m) => m.id === a)?.name ?? a;
      const nameB = MOCK_MEDICINES.find((m) => m.id === b)?.name ?? b;
      results.push({
        level: rule.level,
        medicineA: nameA,
        medicineB: nameB,
        description: rule.description,
        recommendation: rule.recommendation,
      });
    }
  }
  return results;
}

export function findMedicine(id: string): Medicine | undefined {
  return MOCK_MEDICINES.find((m) => m.id === id);
}

export function searchMedicines(query: string): Medicine[] {
  const q = query.trim().toLowerCase();
  if (!q) return MOCK_MEDICINES;
  const scored = MOCK_MEDICINES.map((m) => {
    const name = m.name.toLowerCase();
    const generic = m.genericName.toLowerCase();
    const category = m.category.toLowerCase();
    const effects = m.effects.toLowerCase();
    const ingredients = m.ingredients.join(' ').toLowerCase();

    let score = 0;
    if (name === q) score += 100;
    else if (name.startsWith(q)) score += 50;
    else if (name.includes(q)) score += 30;
    if (generic.includes(q)) score += 20;
    if (category.includes(q)) score += 15;
    if (ingredients.includes(q)) score += 10;
    if (effects.includes(q)) score += 5;
    return { m, score };
  })
    .filter((x) => x.score > 0)
    .sort((a, b) => b.score - a.score)
    .map((x) => x.m);

  return scored;
}
